"""empty message

Revision ID: 16190fdcfe25
Revises: None
Create Date: 2015-01-19 11:03:49.918215

"""

# revision identifiers, used by Alembic.
revision = '16190fdcfe25'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
