"""empty message

Revision ID: 52ac3b3235d5
Revises: None
Create Date: 2015-01-19 11:20:53.576112

"""

# revision identifiers, used by Alembic.
revision = '52ac3b3235d5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
